### ISSUE TITLE
Redundant CIS Deployments in a K8S Cluster

### ISSUE THREAD

**Issue by anjkl** [F5Networks/k8s-bigip-ctlr#1009]
#### Description
As far as I understand k8s-bigip-ctlr doesn't have a leader election mechanism and therefore can only run as a single instance in a cluster.

It may lead to some issues. For example:

The grace period for deleting pods on failed nodes is 5 minutes by default for k8s controller. So when the node where k8s-bigip-ctlr is created falls, k8s-bigip-ctlr will be migrated to another node in 5 minutes. During this period deployments to k8s cluster may lead to application unavailability.

Please provide k8s-bigip-ctlr HA setup capabilities.

#### Kubernetes Version
1.14.6

#### Controller Version
1.9.2

**Comment by sgops** [comment]
+1 for this. This is crucial for us to really use the controller since all of our installations (even our development environments) are F5 BigIP clusters.

Currently we're running two dummy nodes and two bigip controllers with autosync of the datagroup in our lab environment but this is far from ideal.

**Comment by indygoof** [comment]
Without HA for the Controller, this is unfortunately unusable for production environments, and with that, Cloud F5 is currently no choice for being in front of K8s clusters.

**Comment by mdditt2000** [comment]
CIS will be adding a leader election mechanism post CIS 2.1. Moving to a single controller is required for OCP 4.6 and therefore we are looking at either a 2.2 or 2.3 release depending on some upcoming bug fixing. 

However moving to a single controller for a BIG-IP cluster doesn't solve the issue if your Node dies. Even with  single controller for a BIG-IP cluster with leader election mechanism you going to have issues if the node dies. 

Researching what happens if K8S to CIS if the node dies

**Comment by mdditt2000** [comment]
Changed title as this request enhancements is requesting CIS redundancy and has nothing todo with BIG-IP HA or BIG-IP clustering. @anjkl would like multiple CIS instances running in a K8S cluster. Today CIS runs a single instance. Moving to redundant CIS pods in a cluster is something CIS should look at after moving to a single controller for a BIG-IP HA environment. However moving to a single controller for BIG-IP HA is a priority.

**Comment by itsmichaeldayton** [comment]
I am new to CIS.  This issue has been open since Aug 26, 2019?

**Comment by mdditt2000** [comment]
Please review this user-guide for multi-cluster CIS with BIG-IP. https://github.com/mdditt2000/k8s-bigip-ctlr/blob/main/user_guides/multi-cluster/user-guide.md

This architecture provides CIS redundancy, cluster redundancy. If you are looking for BIG-IP HA redundancy with K8S please view the following https://github.com/mdditt2000/k8s-bigip-ctlr/blob/main/user_guides/k8s-ha/README.md

Please note i am working on doing the same content with Calico. This issue can be closed out
