### ISSUE TITLE
k8s-bigip-ctlr allows only AS3 "3.13.0" and below

### ISSUE THREAD

**Issue by L0rdWyd3r** [F5Networks/k8s-bigip-ctlr#1241]
#### Description
Hi all,
I have correclty deployed f5-bigip-ctlr on k8s cluster and f5-appsvcs v3.18.0 on bigip device.
Both workers and masters have no internet access in this case (k8s on prem).
When i try to create ingres using AS3 template in version ("schemaVersion": "3.17.0",) i have fallowing errors but

[ERROR] AS3 Template is not valid. see errors :
[ERROR] - declaration.schemaVersion: declaration.schemaVersion must be one of the following: "3.13.0", "3.12.0", "3.11.0", "3.10.0", "3.9.0", "3.8.0", "3.7.0", "3.6.0", "3.5.0", "3.4.0", "3.3.0", "3.2.0", "3.1.0", "3.0.0"

but when i change version in my configmap from "schemaVersion": "3.17.0" to "schemaVersion": "3.13.0" all works graat, Ingress is up and running on bigip device.

Can someone explain me, whath did i wrong?, despite the fact of having correct version f5-appsvcs (on bigip device) thath should work even with "schemaVersion": "3.18.0" ??

#### Kubernetes Version
v1.16.6

#### Controller Version
v1.14.0

#### Appsvcs rpm Version
v3.18.0

#### BIG-IP Version
BIG-IP 	15.1.0.2 0.0.9

**Comment by trinaths** [comment]
@L0rdWyd3r 
When internet connectivity to fetch latest AS3 schema is not available, we take local schema availble within CIS.

Since AS3 3.13 is LTS and is locally available, CIS uses the same.

When you apply ConfigMap with Schema version 3.17, CIS validates your configMap AS3 with local schema 3.13 where validation fails and above logs the generated. 

However, you can still use AS3 3.18, while aligning to CIS local supported schema version 3.13.
