### ISSUE TITLE
CIS does not honor "servicePort" from ConfigMap AS3 

### ISSUE THREAD

**Issue by mkanade-f5** [F5Networks/k8s-bigip-ctlr#1341]
CIS Version : 2.0      
 Build: f5networks/k8s-bigip-ctlr:2.0       
 BIGIP Version: Big IP 15.1.0.3      
 AS3 Version: 3.18
 Agent Mode: AS3/CCCL       
 Orchestration: OSCP      
 Orchestration Version:4.4.5       
 
 A single Kubernetes service exposed to multiple ports and need to have a single pool with specific port assigned to the BIG-IP . When using the AS3 decelerations in config map and define the pool with servicePort this configuration is not been honored by CIS and a random port from the exposed service is assigned .

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Internal Jira CONTCNTR-1651 for PM tracking

**Comment by mdditt2000** [comment]
No milestone set at this time

**Comment by mdditt2000** [comment]
Issue is resolved in CIS 2.2.1 however please note:

Please note: current design only supports one ConfigMap with one service because of labels used for service discovery on service. However with multiport support CIS will pick up the serviceport defined in configmap and will add the same as pool members. Same service cannot be used for multiple ConfigMaps according to CIS design. CRD don't have this issue as labels are not used for service discovery. This will be documented in clouddocs as a limitation.

I updated the Github issue. This issue can be closed.
