### ISSUE TITLE
Http Basic Authentication 

### ISSUE THREAD

**Issue by jamesDeng** [F5Networks/k8s-bigip-ctlr#1566]
#### Title
 Http Basic Authentication 

#### Description
A small overview of the feature/enhancement proposed

Provide similar nginx ingress controller Basic Authentication feature

https://kubernetes.github.io/ingress-nginx/examples/auth/basic/

#### Actual Problem
It is necessary to add Basic Authentication to kinbana/prometheus dashboard

#### Solution Proposed
https://kubernetes.github.io/ingress-nginx/examples/auth/basic/

#### Alternatives
N/A

#### Additional context
N/A

**Comment by mdditt2000** [comment]
@jamesDeng please use the Telemetry Stream extension to pull kinbana/prometheus stats from BIG-IP. Since the pull consumer will be accessing BIG-IP to gather stats you can setup Basic Authentication. Please review my document that i created for this topic. 

https://github.com/mdditt2000/prometheus

Let me know if you have questions.

**Comment by trinaths** [comment]
Documentation provided helps resolve this issue. Closing this issue now.
