### ISSUE TITLE
BIG-IP Route Domain support for VXLAN based CNIs (flannel on Openshift)

### ISSUE THREAD

**Issue by sokkolchen** [F5Networks/k8s-bigip-ctlr#1604]
#### BIG-IP RD support for XVLAN based CNIs (Flannel on Openshift)

Hi, many Enterprise customers use Route Domains feature to provide network segmentation. Currently k8s-bigip-ctrl is able to support this over AS3 override feature setting default partition Route Domain for Tennant. While VXLAN IP endpoints remain out of this custom partition that makes them placed by CIS only in RD0.
If CIS will have a config item to set this up it then will provide support of Route Domains for Openshift.
Calico is a workaround for applicable k8s environments.

**Comment by mdditt2000** [comment]
@sokkolchen have a few questions on implementation and support for handling Route Domains in OCP/K8S

1) Route Domain will need to be created with an associated tenant/partition. This is created outside of CIS
2) Since CIS uses the AS3 API the route domain is per declaration as a global configuration. Example below

```
"Sample_01": {
     "class": "Tenant",
     "defaultRouteDomain": 1,
```
3) As this configuration is global currently CIS would only be able to support one Route Domain
4) However with the use of a CRD we could add the option for CIS to create that partition/tenant and associate a route domain with it.
5) This will also you for the K8S admin to create many CRDs in OCP and specify what tenant they below. CIS will build that configuration on the BIG-IP in the tenant. 
6) Also whats nice is you can associate that tenant to a K8S namespace that the K8S user is subscribed to.

Please let me know your thoughts before i write up this feature request. Please note would only be implemented in CRDs. Good news is you can use CRDs with OCP.

**Comment by sokkolchen** [comment]
Hi Mark, it is great summary but not exactly for subject i'm asking for. It is nice to have Route Domain control for AS3 created apps in CIS although you comment regarding single domain due to global nature of CIS is not clear as Route Domain could be potentially set with annotation.

Problem actually is not here. All of these can have workaround with AS3 override.

The moment the BIG-IP is connecting to OCP cluster VXLAN-MP is used. https://clouddocs.f5.com/containers/latest/userguide/openshift/#creating-vxlan-tunnels-on-openshift-cluster
it has to be in Common partition to make CIS able to configure it. Thus it has to reside in one single partition (RD0).
Following CIS configuration of Endpoints for CNI is not supporting Route Domain notation IP%RD. So All Endpoints will remain on RD0.
Resulting issue is that regardless that virtual IP can be put into custom Route Domain pool members remain in RD0 that is not really providing a tenancy for BIG-IP.

**Comment by walterk82** [comment]
I have my tunnel built in a custom partition not Common and the FDB is updated accurately.  I can't test multiple route domains at this time, but I'm interested in this topic.  Have you tried to move the tunnel out of Common and see if the using the default route domain on the partition follows suit?

**Comment by mdditt2000** [comment]
@walterk82 you are correct. CIS populates BIG-IP correctly for custom partition. The key is to create the tunnels correctly in the associated tenant. I just documented this https://github.com/mdditt2000/k8s-bigip-ctlr/blob/main/user_guides/multi-cluster/user-guide.md on K8S. 

@sokkolchen we also added route domain support for CRDs https://github.com/F5Networks/k8s-bigip-ctlr/issues/1730

Moving the tunnel to the correct tenant and using the above fix will resolve this issue. Closing this issue
