### ISSUE TITLE
Deploy k8s-bigip-ctlr using the OCP operator

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1680]
#### Setup Details
Build: f5networks/k8s-bigip-ctlr:latest       
OCP version 4.5  
OCP operator 1.4.0  

#### Description  
I originally changed the name of name: f5-server, which I have now learned is a no-no. Unfortunately the deployment the operator created (with the bad name) is hung, even though I uninstall the operator and delete the hung deployment, every time I re-install the operator the previous deployment gets recreated. Any ideas on how to remove/unhook this deployment from the OCP F5 operator permanently?  

#### Steps To Reproduce
1. Install Operator  
```
[@bastion ~]$ oc get deployments --all-namespaces  | grep -i bigip
openshift-operators                                     f5-bigip-ctlr-operator                                  1/1     1            1           10s
```  
2.  Remnant k8s-bigip-ctlr gets started  `ctrl-bigip01-f5-lb-f5-bigip-ctlr`  

```
[@bastion ~]$ oc get deployments --all-namespaces  | grep -i bigip
kube-system                                             ctrl-bigip01-f5-lb-f5-bigip-ctlr                        0/1     1            0           1s
openshift-operators                                     f5-bigip-ctlr-operator                                  1/1     1            1           16s
```

3.  Uninstall Operator  - remnant ctrl-bigip01-f5-lb-f5-bigip-ctlr  remains  

```  
[@bastion ~]$ oc get deployments --all-namespaces  | grep -i bigip
kube-system                                             ctrl-bigip01-f5-lb-f5-bigip-ctlr                        0/1     1            0           11s
```

**Comment by trinaths** [comment]
@grmarxer-1 - This is an expected behaviour when you uninstall and Operator in OCP 4.x platforms. Please refer to docs, https://docs.openshift.com/container-platform/4.4/operators/olm-deleting-operators-from-cluster.html#olm-deleting-operators-from-a-cluster
....
Removing the operator will not remove any of its custom resource definitions or managed resources. If your operator has deployed applications on the cluster or configured off-cluster resources, these will continue to run and need to be cleaned up manually.
....

Closing this issue.
