### ISSUE TITLE
ExternalDNS CRD monitors.

### ISSUE THREAD

**Issue by AlexanderSlinkov** [F5Networks/k8s-bigip-ctlr#1919]
#### Title
ExternalDNS CRD monitors.

#### Description
Hi,

I have a problem adding the DNS monitors via the ExtrnalDNS CRD when my VSs configured in a non-default Route Domain.
The Virtual Server CRD creates appropriate VSs with LTM policies, which contains L7 routing rules. On the LTM level the VSs always have blue square status and they always mark Available by the “bigip” DNS monitor, because of these policies.
So i have to use DNS monitors to get true status of service.
When I trying to use HTTP or HTTPS DNS monitors via the ExternalDNS CRD, they do not work correctly due to custom RDs.
Am I correct or is there another way to do that?

Thanks!

#### Actual Problem
HTTP or HTTPS monitors do not word in RDs with the externaDNS CRD.

**Comment by trinaths** [comment]
Created CONTCNTR-2834 for internal PM tracking

**Comment by lavanya-f5** [comment]
@AlexanderSlinkov  Could you share some details on setup architecture and configuration used

Is it Standalone BIGIP GTM (ltm + gtm ) on same device

**Comment by mdditt2000** [comment]
@AlexanderSlinkov i have taken ownership of the this issue. I would like to recreate tomorrow. Is it Standalone BIGIP GTM (ltm + gtm ) on same device

**Comment by AlexanderSlinkov** [comment]
@mdditt2000 Hi,

Sorry for the delay with the answer.
Yes, both modules (LTM and DNS(formerly GTM)) are on the same device.
Thanks!

**Comment by mdditt2000** [comment]
Thanks will test again on Wednesday

**Comment by mdditt2000** [comment]
Can you please try the following

https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.6/github/1919/cis-deployment/f5-cluster-deployment.yaml

Set the default route domain in the CIS argument to your spec 

Example

```
- "--default-route-domain=10"
```

Setup the correct vlan for health monitor. Also please note. Please use the build in my CIS deployment due to bug in CIS with regards to EDNS monitors. 

```
image: "amit49g/k8s-bigip-ctlr:build-1"
```

Working example

https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.6/edns

**Comment by trinaths** [comment]
Based on the above solution provided, closing this issue.
