### ISSUE TITLE
Allow to configure a specific HTTP profile in VirtualServer CRD

### ISSUE THREAD

**Issue by melkypie** [F5Networks/k8s-bigip-ctlr#1926]
#### Title
Allow to configure a specific HTTP profile in VirtualServer CRD

#### Description
Currently only the default http profile can be used and it could be good if we could use an http profile already defined in big-ip (or even have a HTTPProfile CRD).

#### Actual Problem
HTTP profiles have a ton of configurable parameters that are useful to change and having only the default http profile be defined when using a CRD is quite a drawback for some services.

#### Solution Proposed
Add an option to VirtualServer CRD to define a reference to an http profile (similar to how it is done with a waf policy or irules).

#### Alternatives
Using configmaps

**Comment by trinaths** [comment]
Policy CRD is being designed to capture this requirement.

**Comment by kudiyarov** [comment]
Hi team!
Is there estimated date when this feature becomes available?

**Comment by mdditt2000** [comment]
This issue is resolved in CIS 2.7. Please sure policy CRD to create the custom HTTP policy. Example

https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.7.1/two/crd/vs

Question, http profile for the same for both client/server as shown below:

![image](https://user-images.githubusercontent.com/12733938/154554652-fc435cc2-c6be-4887-8a30-71c6adf80dfa.png)

Requirement to have different HTTP profiles for client/server?

**Comment by mdditt2000** [comment]
Added additional feature in CIS 2.9. You can now create both client/server for TCP and HTTP Profile. 

Closing out.
