### ISSUE TITLE
Business Interruption caused by Deployment Rolling Update

### ISSUE THREAD

**Issue by gazhuchao** [F5Networks/k8s-bigip-ctlr#2200]
####Setup Details
CIS Version : 2.7.0
Build: f5networks/k8s-bigip-ctlr:2.7.0
BIGIP Version: BIG-IP 15.1.4 Build 0.0.47 Final
AS3 Version:3.28.0
Agent Mode: Configmap + AS3
Orchestration: K8S
Pool Mode: Cluster 
 Additional Setup details: <CNI: Calico BGP>

#### Description  
 When Deployment starts rolling update all pods for software upgrade, The time it takes to complete the rolling update of pods is T1. 
  At the same time, CIS is watching the changes to K8S cluster resources. CIS will write to the front-end VE through AS3 when BIGIP-related resource changes are detected. The time it takes for configuration changes to complete on BIGIP is T2.
  If T2 > T1, there will be a situation where the POD update is complete, but the configuration on BIGIP has not changed. It can lead to critical business interruptions.
  There are two reasons for this issue:
  1. Since CIS updates BIGIP configuration and POD rolling updates are asynchronous, there is no any mechanism to guarantee the sequential relationship between this two；
  2. CIS performance issues caused BIGIP configuration changes to take too long to complete.

  In my lab, I have created 120 vs which in 20 partitions on VE. When I changed a deployment image, the deployment completed the rolling update in less than 10 seconds, but it took 110 seconds to update the POD address on VE, it causing service interruption for 100 seconds.

   This issue has been reported in https://github.com/F5Networks/k8s-bigip-ctlr/issues/1359.

#### Steps To Reproduce
1)  Deploy 120 vs in 20 NS (Partitions);
2)  Select a deployment, and change it's image, then it will rolling update; 
3)  After about 10s, deployment completed rolling update, but the configuration of VE cannot be changed in time;
4)  The business is interrupted until the configurations on the VE are changed. The interruption time is about 100 seconds.

#### Expected Result 
Avoid Business Interruption

#### Actual Result  
The interruption time is about 100 seconds in the lab.

**Comment by walterk82** [comment]
Do you use health monitors for the individual pools/pods?

**Comment by gazhuchao** [comment]
Yes, I use TCP monitor, and use the default interval time. Within 10 seconds after the scrolling update is complete, all pool members are identified as unavailable.

**Comment by trinaths** [comment]
@gazhuchao - Can we have https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#proportional-scaling of the deployment to mitigate this issue ? or Deployment strategyType ?

**Comment by gazhuchao** [comment]
I don't think this is helpful. The reasons for the  issue as below:
1. Since CIS updates BIGIP configuration and POD rolling updates are asynchronous, there is no any mechanism to guarantee the sequential relationship between this two；
  2. CIS performance issues caused BIGIP configuration changes to take too long to complete.

**Comment by trinaths** [comment]
Created CONTCNTR-3137 for internally tracking to validate this issue based on fix to CONTCNTR-3081.

**Comment by trinaths** [comment]
@gazhuchao  please validate this requirement with 2.7.1 CIS release

**Comment by gazhuchao** [comment]
The issue remains in 2.7.1.

**Comment by gazhuchao** [comment]
The issue remains in 2.7.1.

**Comment by trinaths** [comment]
Created [CONTCNTR-3188] for internal PM tracking.

**Comment by zongzw** [comment]
Tested with the following 3 scenarios, 

* Replicas +1:
   There will be no business interruption.
   The pod(service) becomes available in K8s before the endpoint change being reflected on BIG-IP.
   Business is provided by original pods until the traffic link is setup on BIG-IP(member+arp).
* Replicas -1:
   There will be business interruption, but very short, can be ignored.
   The business interrupts because pod removal. But this interruption will be immediately be eliminated by BIG-IP's healthmonitor.
   Later, the stale traffic link for the removed pod will be removed from BIG-IP by CIS.
* Image update:
  There will be long term business interruption.
  Because:

![图片](https://user-images.githubusercontent.com/17761849/160529625-f8451519-9b77-4cb3-a9b3-15fc0de64af1.png)

**Comment by olvandeng** [comment]
@trinaths @mdditt2000 We investigate the GitHub #2200 and the initial findings are in Andrew Zong's comment, it is a complicated problem, and critical to customers in rolling update scenario. Could you prioritize the GitHub issue #2200 ASAP so we could work with CIS HYD Engineering team to resolve it together. Thanks.

**Comment by trinaths** [comment]
@olvandeng - Thanks a bunch for sharing your findings. Recommend share a PR so that the team can review your suggestions. This would help resolve this issue in a effective way.

**Comment by zongzw** [comment]
I don't think there is a good way to solve this problem because it's related to CIS architecture. That means the root of CIS.
I did the above analysis to show you the obstacle.
2 months past, I suppose you team have some proposal already. What do you think about this issue?

**Comment by trinaths** [comment]
@zongzw - This is an RFE and its in the backlog. We request your PR for this issue so that we can review and discuss the solution further. We cannot redesign and change algorithms for 1 issue.

**Comment by trinaths** [comment]
> Tested with the following 3 scenarios,
> 
> * Replicas +1:
>   There will be no business interruption.
>   The pod(service) becomes available in K8s before the endpoint change being reflected on BIG-IP.
>   Business is provided by original pods until the traffic link is setup on BIG-IP(member+arp).
> * Replicas -1:
>   There will be business interruption, but very short, can be ignored.

@zongzw  Can you give the time taken for ` very short` ?

>   The business interrupts because pod removal. But this interruption will be immediately be eliminated by BIG-IP's healthmonitor.
>   Later, the stale traffic link for the removed pod will be removed from BIG-IP by CIS.
> * Image update:
>   There will be long term business interruption.

`long term` please provide time taken

>   Because:
> 
> ![图片](https://user-images.githubusercontent.com/17761849/160529625-f8451519-9b77-4cb3-a9b3-15fc0de64af1.png)

**Comment by zongzw** [comment]
Again, I don't have the PR specific for this issue. Again, this is not as simple as a normal issue that normal PR can fix IMO. But it may have big influence, because of it, K8S feature -- rolling update ability is terminated when using BIG-IP.
The essential gap of this issue is that BIG-IP is an 'external' device providing ADC ability(LB/Ingress/or so..)
In my opinion, I think this can been considered as an functional issue, but fortunately, can be eliminated with performance tuning effort.
So, I highly recommend you team to review PR #2292. This is a not-so-big change but has very good performance result. Thus, the "business interruption" duration can be reduced greatly, reason is simple, CIS works faster, less network accessing waiting.
The change happens only in `getEndpoints` function. As I mentioned long ago in our initial communication: **using `informer cache` instead of `kubeclient`**. It will give us great performance benefit! It's also the right way of integrating with customer's K8S production.
Another PR #2300, also help a lot. Repeatedly doing jsonschema check is a huge time waste. See it for details.

**Comment by zongzw** [comment]
`very short`: 1 time access, or 1 second
`long term`: 15 seconds -- only one group of resources(vs/pool/member/..) in a fresh env, image prepared in-place.

The situation become worse and worse quickly if groups grow.

**Comment by trinaths** [comment]
@zongzw  PR #2292  and #2300 are newly created and will be reviewed in upcoming sprints.

**Comment by trinaths** [comment]
> Again, I don't have the PR specific for this issue. Again, this is not as simple as a normal issue that normal PR can fix IMO. But it may have big influence, because of it, K8S feature -- rolling update ability is terminated when using BIG-IP. The essential gap of this issue is that BIG-IP is an 'external' device providing ADC ability(LB/Ingress/or so..), CIS cannot do exactly fast whenever K8s event comes. In my opinion, I think this can been considered as an functional issue, but fortunately, can be eliminated with performance tuning effort. So, I highly recommend you team to review PR #2292. This is a not-so-big change but has very good performance result. Thus, the "business interruption" duration can be reduced greatly, reason is simple, CIS works faster, less network accessing waiting. The change happens only in `getEndpoints` function. As I mentioned long ago in our initial communication: **using `informer cache` instead of `kubeclient`**. It will give us great performance benefit! It's also the right way of integrating with customer's K8S production. Another PR #2300, also help a lot. Repeatedly doing jsonschema check is a huge time waste. See it for details.

@zongzw agree. This is an RFE for CIS since can be an behavioural change.

**Comment by zongzw** [comment]
After some more investigation, we may use ![finalizers](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) to solve this problem.
`metadata.finalizers` is the very way of suspending deletion.
It's a 'pre-delete' hook to remove the association between K8S resource definitions and resource's external implementations(on BIG-IP).

The example of using it: https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/

The shortages of this way are that
1) either: User create resources with `metadata.finaizers` appointed. 
    or: CIS is responsible for setting `metadata.finalizers` when mapping them to BIG-IP resources[recommended personally].
2) extra coding effort: `finalizers` controller implementation inside CIS.

**Comment by braunsonm** [comment]
Can you use a PDB instead? Finalizes I don't think are meant for disruptions.
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets

**Comment by zongzw** [comment]
@braunsonm thanks for your suggestion. However, it's not the case PDB can cover. Because,
In this issue case, we are using BIG-IP as the ingress of the pods. 
For these pods, in fact, there is no pod voluntary disruption. 
They are correctly, new pods created, old ones evicted. 
The issue happens because the ingress meta-info on BIG-IP were not timely updated.
You may refer to my former comment(with the sequence chart).
