### ISSUE TITLE
Helm chart does not allow setting tolerations

### ISSUE THREAD

**Issue by braunsonm** [F5Networks/k8s-bigip-ctlr#2290]
#### Description  
 Although you can set node affinity, you can't actually schedule this on control plane nodes because there is not way to add tolerations.

This should be possible so that the workload can be scheduled on system nodes which tend to be more stable in deployments as they do not grow and shrink as often in deployment scaling.

**Comment by mdditt2000** [comment]
Requirement - Expose options to run CIS on the controller nodes. Must be configured via Helm Chart

**Comment by mikejoh** [comment]
@braunsonm Maybe this issue isn't valid anymore, but there's been a way of configuring `tolerations` in the k8s-bigip-ctlr chart  since at least two years AFAICT!

See this https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ctlr/README.md#chart-parameters and here https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml#L119-L122.

The provided [`values.yaml`](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/helm-charts/f5-bigip-ctlr/values.yaml) file doesn't reflect this though, some things are, there's some comments in that file that covers some of the configuration options.

**Comment by braunsonm** [comment]
Oh interesting thanks @mikejoh 
I probably just didn't know since it isn't in the values file
