### ISSUE TITLE
Can WAF policies be added per prefix when using Openshift routes

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2765]
#### Setup Details
 CIS Version : 2.11.1
Build: f5networks/k8s-bigip-ctlr:2.11.1
BIGIP Version: BIG-IP 16.1.2.1 Build 0.0.10 Point Release 1
AS3 Version: 3.41
Agent Mode: CR
Orchestration: K8S
Orchestration Version: 1.25.4
Pool Mode: Cluster
Additional Setup details: K8s version 1.25.4, flannel

#### Description  
 Is it possible to add existing WAF policies per prefix when creating Openshift routes, like in this example: https://github.com/mdditt2000/k8s-bigip-ctlr/tree/main/user_guides/routes-externaldns-waf 

#### Steps To Reproduce
N/A

#### Expected Result 
N/A

#### Actual Result  
N/A

#### Diagnostic Information
N/A
#### Observations (if any)
N/A

**Comment by trinaths** [comment]
Fixed in 2.12. Recommend use NextGen Routes. See https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/next-gen-routes/routes/sample-route-with-waf-annotation.yaml and https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/next-gen-routes/configmap/extendedRouteConfig.yaml
