### ISSUE TITLE
Add annotation for assigning IP address for service type load balancer

### ISSUE THREAD

**Issue by avinashchundu9** [F5Networks/k8s-bigip-ctlr#3329]
#### Title
Add annotation for assigning IP address for service type load balancer

#### Description
Currently, for service type load balancer we can't assign IP addresses manually. It can only be assigned by the IPAM. Adding the annotation "cis.f5.com/ipaddress: xx.xx.xx.xx" will give the ability for users to use static IP addresses and reuse them during migrations. This will remove dependency on IPAM installation and maintenance. This will also enable users to deploy helm charts that defaults the configuration to service type load balancer without modifying them to custom resources.

#### Actual Problem
Currently, IPAM is mandatory for service type load balancer, and control on which IP address we can use or reuse is limited. I understand custom resources are an option but most users want to deploy their applications using service type LB before they want to get into custom settings.

#### Solution Proposed
Add annotation "cis.f5.com/ipaddress: xx.xx.xx.xx" for service type load balancer

**Comment by mdditt2000** [comment]
@avinashchundu9 thanks for opening this issue. @trinaths  we spoke about this yesterday. Agree i like this enhancement 

Next steps to create a Jira task and prioritize for 2.17

**Comment by avinashchundu9** [comment]
Also please consider adding annotation for partition as well.

**Comment by trinaths** [comment]
Fixed in 2.16.1

**Comment by mikeoleary** [comment]
Hi @mdditt2000 and @trinaths 

I have a customer that now appears to have a problem due to this update made in CIS 2.16. This issue above was opened because OP said _"Currently, for service type load balancer we can't assign IP addresses manually. "_ - but in the experience of my customer that was not true.

My customer _was_ defining their IP addresses manually by manually defining the field **spec.loadBalancerIP**, which is valid in the spec of a LB service.

They were doing this with version 2.15 and CIS was working fine, processing services of type LB and creating the required VS's on BIG-IP.

In 2.18 they are now forced into a new choice: use an annotation or use IPAM. `spec.loadBalancerIP` no longer seems to work.

This customer deploys multiple services of type LB via a Helm chart (Redis), and that helm chart does not give them the ability to define a specific annotation per LB service. It _does_ allow them to define specific values of `spec.loadBalancerIP` for each of these services. IPAM doesn't give them an easy way to define a specific IP address, which they want due to firewall rule requirements.

Ask: can we have CIS process services of type LB using the `spec.loadBalancerIP` field for the IP address? We believe this was possible in v2.15 and now in v2.18 it is not.
