### ISSUE TITLE
Set insecureEdgeTerminationPolicy to Redirect in one edge route but affect all other edge route

### ISSUE THREAD

**Issue by lihongan** [F5Networks/k8s-bigip-ctlr#341]
Set insecureEdgeTerminationPolicy to Redirect in one edge route, it can work. But all other edge route even in different namespace also have the ability to redirect HTTP client connections to HTTPS.

If set insecureEdgeTerminationPolicy to Allow in one edge route, it only affect that route as expected.

**Comment by f5gary** [comment]
This is working as designed. The OpenShift F5 Router currently does not support HTTP redirects for the F5 BIG-IP at all, but this controller offers improved support by configuring an iRule on the HTTP virtual server. Since there is one HTTP virtual server for all routes, once any route is configured to redirect HTTP they all do. In the future, this feature can be enhanced such that only edge routes configured with InsecureEdgeTerminationPolicy == Redirect will be redirected.

**Comment by amudukutore** [comment]
We recognize this is a limitation in the current version, and will address this in the next release. Downgrading to a P3.
