### ISSUE TITLE
Kubernetes Ingress - Dynamic IP allocation

### ISSUE THREAD

**Issue by davisvansant** [F5Networks/k8s-bigip-ctlr#445]
#### Description

We are currently looking to utilize our F5s as Ingress controllers for our on prem K8s deployments - so far in testing, everything is looking solid!

What I'm currently looking for right now are options/solutions to dynamically allocating and provisioning IPs that can be used as part of the annotation `virtual-server.f5.com/ip`, found here 

 - http://clouddocs.f5.com/containers/v1/kubernetes/kctlr-ingress.html#quick-start

There may be options around using a single IP and either `Simple Fanout` or `Name-based virtual hosting`, but I'm really digging for a solution that can take advantage of both (or combination of the 3) and basically consume IPs from a pool of available IPs - something similar to DHCP, but for Ingress controllers. What would be really awesome is to have this solution dynamically provision the Ingress controller, and in turn pass back a dynamic DNS entry of the endpoint, and when done, cleanup

 - https://github.com/kubernetes-incubator/external-dns

This is all still in development for us (but are looking to release to production soon!), but I'm just looking for solutions and understanding on the best path forward for what we can do right now, and perhaps start preparing for where we can go for future iterations.

#### Kubernetes Version
Rancher `v1.6.10`, Kubernetes `v1.7.7-rancher1`

#### Controller Version
`f5networks/k8s-bigip-ctlr:1.2.0`

#### BIG-IP Version
` BIG-IP 11.6.0 Build 0.0.401 Final `

Let me know if I can help in any way - thanks so much!

**Comment by f5yacobucci** [comment]
Hi, is the proposal here for the k8s-bigip-ctlr to be configured with an IP block which it will choose from and configure DNS for the new service? Or for a separate controller which can manage IP and DNS?

We'd like to shy away from management of this sort at the k8s-bigip-ctlr layer. The intention is to take all control plane direction from the orchestration system; it's the sole control plane. This allows for the controller to be stateless and to recover from failure without needing to possibly reconfigure any objects because different decisions are made - or without needing another backend store. For instance, on restart it's difficult to know which IP address was previously chosen for a Service. I think there are solutions but it's a complexity we'd like to avoid.

Ideally (from our perspective) a combination of an IPAM, external-dns, and the k8s-bigip-ctlr would be employed.

**Comment by davisvansant** [comment]
Hi @f5yacobucci !

So my apologies if I derail this too much here, but let me see if I can focus this down a bit more

 - I'm just simply looking for a solution that can dynamically allocate IPs that are provisioned as our K8s Ingress Controller

Consider this scenario

>We have a single K8s cluster per site, multiple teams will be using this. They may or may not have their own `namespace` in this K8s cluster, but for the sake of this scenario, lets say they do. We know that our F5/K8s controller can manage this, so we have some wins there! However, lets just say each of these teams want to manage a set of their own services and expose these services internally for other teams to view, and potentially something that would be exposed externally. In this scenario, each of these teams would need to expose their set of services, and would in turn need an IP address. This IP address would have to be placed in their manifests and would have to be "controlled" so as to not conflict/collide with others

Understandably, this may not be exactly what happens, but either way, I'd like to try and prepare for something like this, or see if its at all possible. Most of the concepts mentioned above are just that, concepts, and designed to help come up with creative solutions to potentially solve this, even if it takes a combination of x to get there

Let me know if I can help answer any questions here

Thanks!

**Comment by trinaths** [comment]
IPAM project is archived now. and CIS doesn't support such scenario.
