### ISSUE TITLE
[DOC] Clarification in namespace to be used for BIG-IP controller installation

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#610]
#### Description

**Please note that this is about BIG-IP controller installation only**

In http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html we indicate "You should create all BIG-IP Controller resources in the kube-system namespace unless otherwise specified".

I don't find anywhere if we do allow installing the BIG-IP controller in any other namespace.

If we don't allow installing the the BIG-IP controller in any other namespace I would rather say something like "The BIG-IP controller needs to be installed in kube-system namespace, applications can be deployed in any namespace". This would be less confusing IMHO.

On the other hand I have tested deploying the BIG-IP controller in a random namespace, and there is no problem doing so as long as it is understood that BIG-IP controller will only be able to operate with applications in that namespace. Could you please indicate in the documentation if this is a supported configuration?

#### Controller Version

1.4.2

**Comment by tomminux** [comment]
I do agree, we should be as clear as possible on different architectures we could put in place when integrating F5 BIG-IP with k8s and our F5 CC.  As far as I can understand right now, it would make sense to have a CC in every namespace, each of them talking to a separate partition/big-ip

**Comment by alonsocamaro** [comment]
If deploying the controller in a specific name space is supported then we probably should also take care of our RBAC sample configs. I find we should do the following modifications:

- From: ```kind: ClusterRole``` to ```kind: Role``` and,

- From  ```kind: ClusterRoleBinding``` to  ```kind: RoleBinding```

**Comment by jputrino** [comment]
We recommend that users install the controller in the kube-system namespace because that is where all other kubernetes controllers run. It is not a requirement, though, and users can install the controller in any namespace they want to. We do have a WIP explanation of this in flight in a new multi-tenancy doc in the f5-ci-docs repo. 

@alonsocamaro, you can review it here:
https://github.com/jputrino/f5-ci-docs/blob/ha-docs/docs/kubernetes/kctlr-multi-tenancy.rst

We should also clarify the installation doc (which lives in the docs repo:  https://github.com/F5Networks/f5-ci-docs/blob/master/docs/kubernetes/kctlr-app-install.rst).

**Comment by alonsocamaro** [comment]
@jputrino I like the doc. I would just add some explicit clarification that the "1 partition and 1 Controller per ..." refers to a single BIG-IP. Given that installing a BIG-IP in a standalone configuration is not normal this should be clarified. This might be obvious for us but maybe not for new customers.

**Comment by jputrino** [comment]
Issue moved to [F5Networks/f5-ci-docs #390](https://github.com/F5Networks/f5-ci-docs/issues/390) via [**ZenHub**](https://www.zenhub.com/)
