### ISSUE TITLE
BigIP-Ctlr deletes "Data Group Lists"

### ISSUE THREAD

**Issue by preisbeck** [F5Networks/k8s-bigip-ctlr#626]
#### Description

We share a BigIp cluster between multiple Kubernetes clusters, the separation is done through the use of user partitions. The k8s clusters share a single iApp that manages the content of every cluster. So far pretty standard.
I just ran into problems when we tried to set cluster specific default values for the IApp in "Data Group Lists" and store them in the cluster specific partitions, because currently the BigIP controller deletes everything on a given partition. This is fine for virtual server, pools, nodes and all other dynamic items that are actually controllable via the BigIP-Ctrl, but is a bit counter intuitive for things the BigIP-Ctrl can't control. 
Data Group Lists for example are static information, and it would be nice to be able to prevent them from becoming deleted by it.
Is it realistic that we see this kind of functionality in future releases, otherwise I would work around this problem with different DG in the Common partition on include a logic in the IApp to choose between them.

#### Kubernetes Version
1.9.2

#### Controller Version
1.4.2

#### BIG-IP Version
12.1.3 Build 0.5.378

**Comment by russokj** [comment]
Our next release will allow for certain Big-IP LTM resources to  pre-existing (and post-existing) in the controller's partition.  In order to provide this feature, the resource must have a metadata attribute that the controller will monitor.  At this time only a few of the Big-IP resources support the attribute (virtual servers, virtual addresses, pools, etc).  The data group does not support it so you must use the common partition.

**Comment by preisbeck** [comment]
Hi @russokj,
Thank you very much for the quick response. I'll close the Issue as the missing metadatas aren't anything the bigip-ctlr could fix.

greetings
Phillip
