### ISSUE TITLE
Define SSL profile via bigip-ctlr

### ISSUE THREAD

**Issue by roldancer** [F5Networks/k8s-bigip-ctlr#688]
Hi All, I would like to know if it is possible to define a SSL profile via bigip-ctlr ?

We use Openshift, we have lot of routes with different cypher suite and  TLS requirements, we need define different ssl profiles an attach them to the routes, is it possible ?

Many thanks.

**Comment by amudukutore** [comment]
I believe [this](http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.5/#supported-route-configurations) section in the documentation addresses your questions.

**Comment by roldancer** [comment]
oki, cool. by the way is there any way to choose the parent ssl profile via Route annotation?

Thanks.

**Comment by rsalsa** [comment]
@roldancer - can you explain a bit more what you'd like to do? The following annotations select the profile to use:

`virtual-server.f5.com/clientssl`
`virtual-server.f5.com/serverssl`

**Comment by roldancer** [comment]
Hi @rsalsa we would like to define by 3 kind of ssl profiles, low, medium and strong, so at the Route level with an annotation we would like to choose the **parent ssl profile** I mean (low, medium or strong).

Thanks.

**Comment by mdditt2000** [comment]
@palonsoro @roldancer CIS 1.9 with AS3/Configmap the controller can now send a declaration to the BigIP and create the SSL profile. Example https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-9/A2/f5-as3-configmap.yaml

OpenShift route implementation will be adopted in CIS 1.10 using a simple annotation of the SSL policy. Since we going to be using AS3 on the backend the SSL profile is still automatically configured by the controller, from the certificates specified at the route, using the clientssl parent SSL profile. The clientssl parent can have the associated ciphers etc. This feature in coming mid July.

**Comment by mdditt2000** [comment]
Issues resolved in CIS 1.10 beta image available at https://github.com/mdditt2000/openshift/blob/dev/cis-1-10/modify-routes.md

**Comment by ssurenr** [comment]
Blocked by https://github.com/F5Networks/f5-appsvcs-extension/issues/201

**Comment by mdditt2000** [comment]
Resolved in CIS 1.14
Added optional command line arguments to support TLS version and Ciphers.
–tls-version to enable specific TLS version 1.2/1.3 on BIG-IP. Default 1.2
–ciphers to configure cipher suite on BIG-IP. Option valid for TLSv1.2
–cipher-group to configure a cipher-group on BIG-IP. Option valid for TLSv1.3
Note: both –ciphers and –cipher-group are mutually exclusive based on the TLS version.

Also resolved F5Networks/f5-appsvcs-extension#201 using AS3-18 and AS3 configmap for multiple SSL profiles. CIS 2.0 will pickup support for AS3-18 which will allow you to combined a route + AS3 override.
