### ISSUE TITLE
Enhancement Request: allow non-admin role for the k8s BIG-IP user

### ISSUE THREAD

**Issue by litmaj0r** [F5Networks/k8s-bigip-ctlr#695]
#### Description
A customer would like to set more restrictive permissions for the BIG-IP user that k8s-bigip-ctlr uses to interact with configuration objects on the BIG-IP for security reasons. Currently, only the Administrator role is supported and only certain configuration objects (i.e. items like Virtual Servers and nodes) in the k8s-managed partition) can be controlled by another role but not the comprehensive set of configuration objects k8s-bigip-ctlr needs to manage.

==== RFE Template ====
1. Describe the new feature in as much detail as possible.
In the current implementation of the F5 Kubernetes controller (http://clouddocs.f5.com/containers/v2/kubernetes/), F5 requires that the account the controller uses to connect to the F5 have Resource Administrator or Administrator permissions.  Since the controller requires a dedicated partition to perform its configuration in, the customer would like to allow the controller to use an F5 account that is constrained to ONLY act upon that partition.  The current account has too many permissions right now.

2. What is the problem that would be resolved by adding this new feature?
If there is a bug in the controller code or the F5 BIG-IP user account is compromised, the compromise could affect any resource on the F5.  This includes objects in the Common partition, which is where core configuration may be stored.  The customer would like to eliminate this possibility by reducing the permissions this account has down to the dedicated partition and/or configuration objects its allowed to manage.

3. What is the business impact to your site due to the lack of this?
Increased security, decreased risk, and reduced surface attack area when implementing the F5 Kubernetes controller.

#### Kubernetes Version
v1.8.x

#### Controller Version
1.5.0

#### BIG-IP Version
v13.x

#### Diagnostic Information
Here is some additional information related to this request, for easier reference: 

BIG-IP Roles for 13.x:
https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-user-account-administration-13-0-0/3.html

Current k8s-bigip-ctlr requirements:
http://clouddocs.f5.com/containers/v2/kubernetes/
"Important: The BIG-IP Controller requires Administrator permissions in order to provide full functionality."

**Comment by sfudeus** [comment]
Same for us even with k8s 1.15 and bigip-ctrl 1.9. We are working with resource-admin, but really would like to use a role which is restricted to a single partition, since it should only manage virtualservers/addresses/pools within that single partition. 
Using AS3 makes the issue even worse, where resource admin is not sufficient.

**Comment by trinaths** [comment]
CIS doesn't support this. Closing the issue.

**Comment by sfudeus** [comment]
@trinaths 
I think it is clear that CIS does not support this - otherwise this issue would not exist (which is an Enhancement Request).

So is the message in fact the following? 
> We do not intend to implement this in the future.


IMHO that would shed a bit of bad light from a security perspective, since it violates the least privilege principle. 
For sure, to use the full spectrum of AS3 you need full privileges. But for use-cases where only items within a single partition are created, single-partition privileges would be sufficient, wouldn't they?

**Comment by mdditt2000** [comment]
HI @sfudeus CIS uses the AS3 API to configure BIGIP which requires admin creds. At this time there is no work around.
