### ISSUE TITLE
CC in other ns keep deleting the static arp 

### ISSUE THREAD

**Issue by myf5** [F5Networks/k8s-bigip-ctlr#804]
#### Description
====flannel vxlan network=====
1. Create a cc to monitor the "default" ns
2. Create a cm in the default ns, the cm select a service which in the default ns
===>Everything work well.
3. Create a new cc to monitor "cka" ns, the cc self is in kube-system ns
===>Everything work well. No arp was deleted in bigip
4. Create a new cm in cka ns, it reference the same service as the step 2 （usually we should not reference resource across NS）
===>The cc in the cka ns starts to delete arp entries as it can not find the service.
===>The cc in the default ns will re-add the arp entries.
===>Looping,  cc in cka delete arp, cc in default re-add arp
5. Delete the cm in cka ns (which created in step 4)
===> Looping continue.  (same behavior as before), why it keep deleting even I had deleted it.

#### Kubernetes Version
1.10

cc yaml for step1 :
```
[root@k8s-master f5-k8s]# cat bigip-ctlr-deployment.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "myf5/k8s-bigip-ctlr:1.7.1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
            - name: TZ
              value: Asia/Shanghai
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=172.16.20.202",
            "--bigip-partition=k8s",
            "--namespace=default",
            "--pool-member-type=cluster",
            "--flannel-name=/Common/flannel_vxlan",
            ]
      imagePullSecrets:
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login

```

cm for step 2:
```
[root@k8s-master f5-k8s]# cat f5-vs.yaml 
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-deploy-svc.vs
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "nginx-deploy-svc",
          "healthMonitors": [{
            "interval": 15,
            "protocol": "http",
            "send": "GET / HTTP/1.1\r\nConnection: close\r\nHost: 1.1.1.1\r\n\r\n",
            "recv": "cka",
            "timeout": 30
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "172.16.40.80"
          },
          "partition": "k8s",
          "balance": "least-connections-member",
          "mode": "http"
        }
      }
    }

```

cc for step3:
```
[root@k8s-master f5-k8s]# cat bigip-ctlr-deployment-cka-ns.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deploy-ns-cka
  namespace: kube-system
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr-ns-cka
      labels:
        app: k8s-bigip-ctlr-ns-cka
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr-ns-cka
          image: "myf5/k8s-bigip-ctlr:1.7.1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
            - name: TZ
              value: Asia/Shanghai
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=172.16.20.202",
            "--bigip-partition=cka",
            "--namespace=cka",
            "--pool-member-type=cluster",
            "--flannel-name=/Common/flannel_vxlan",
            ]
      imagePullSecrets:
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login

```

cm for step 4:
```
[root@k8s-master f5-k8s]# cat f5-vs-ns-cka.yaml 
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-deploy-svc-cka.vs
  namespace: cka
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "nginx-deploy-svc",
          "healthMonitors": [{
            "interval": 15,
            "protocol": "http",
            "send": "GET / HTTP/1.1\r\nConnection: close\r\nHost: 1.1.1.1\r\n\r\n",
            "recv": "cka",
            "timeout": 30
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "172.16.40.80%10"
          },
          "partition": "cka",
          "balance": "least-connections-member",
          "mode": "http"
        }
      }
    }

```
logs of cc in the default:
```
2018/12/29 23:42:06 [INFO] [2018-12-29 23:42:06,749 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:42:36 [INFO] [2018-12-29 23:42:36,692 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:42:36 [INFO] [2018-12-29 23:42:36,722 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:43:06 [INFO] [2018-12-29 23:43:06,711 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:43:06 [INFO] [2018-12-29 23:43:06,740 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:43:36 [INFO] [2018-12-29 23:43:36,733 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:43:36 [INFO] [2018-12-29 23:43:36,768 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:44:06 [INFO] [2018-12-29 23:44:06,716 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:44:06 [INFO] [2018-12-29 23:44:06,748 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:44:36 [INFO] [2018-12-29 23:44:36,713 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:44:36 [INFO] [2018-12-29 23:44:36,743 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:45:06 [INFO] [2018-12-29 23:45:06,740 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:45:06 [INFO] [2018-12-29 23:45:06,770 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:45:36 [INFO] [2018-12-29 23:45:36,721 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:45:36 [INFO] [2018-12-29 23:45:36,754 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:46:06 [INFO] [2018-12-29 23:46:06,744 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:46:06 [INFO] [2018-12-29 23:46:06,774 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:46:36 [INFO] [2018-12-29 23:46:36,749 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:46:36 [INFO] [2018-12-29 23:46:36,781 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
2018/12/29 23:47:06 [INFO] [2018-12-29 23:47:06,746 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
2018/12/29 23:47:06 [INFO] [2018-12-29 23:47:06,778 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18

```

logs of the cc in the cka ns:
```
2018/12/29 23:29:48 [INFO] Port '80' for service 'nginx-deploy-svc' was not found.
2018/12/29 23:29:48 [INFO] Service 'nginx-deploy-svc' has not been found.
2018/12/29 23:29:50 [INFO] [2018-12-29 23:29:50,272 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:29:50 [INFO] [2018-12-29 23:29:50,307 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:30:18 [INFO] Port '80' for service 'nginx-deploy-svc' was not found.
2018/12/29 23:30:18 [INFO] Service 'nginx-deploy-svc' has not been found.
2018/12/29 23:30:20 [INFO] [2018-12-29 23:30:20,288 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:30:20 [INFO] [2018-12-29 23:30:20,330 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:30:48 [INFO] Port '80' for service 'nginx-deploy-svc' was not found.
2018/12/29 23:30:48 [INFO] Service 'nginx-deploy-svc' has not been found.
2018/12/29 23:30:50 [INFO] [2018-12-29 23:30:50,270 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:30:50 [INFO] [2018-12-29 23:30:50,306 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:31:18 [INFO] Port '80' for service 'nginx-deploy-svc' was not found.
2018/12/29 23:31:18 [INFO] Service 'nginx-deploy-svc' has not been found.
2018/12/29 23:31:20 [INFO] [2018-12-29 23:31:20,270 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:31:20 [INFO] [2018-12-29 23:31:20,311 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:31:40 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2018/12/29 23:31:50 [INFO] [2018-12-29 23:31:50,285 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:31:50 [INFO] [2018-12-29 23:31:50,324 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:32:20 [INFO] [2018-12-29 23:32:20,280 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:32:20 [INFO] [2018-12-29 23:32:20,318 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:32:50 [INFO] [2018-12-29 23:32:50,334 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:32:50 [INFO] [2018-12-29 23:32:50,375 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:33:20 [INFO] [2018-12-29 23:33:20,271 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:33:20 [INFO] [2018-12-29 23:33:20,306 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
2018/12/29 23:33:50 [INFO] [2018-12-29 23:33:50,281 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
2018/12/29 23:33:50 [INFO] [2018-12-29 23:33:50,316 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
```

#### Controller Version
1.7.1

**Comment by vincentmli** [comment]
which namespace your service "nginx-deploy-svc" in ?

**Comment by vincentmli** [comment]
I assume if your service "nginx-deploy-svc" is in namespace "k8s", but not exist in namespace "cka", it could cause problem because the one  k8s-bigip-ctrl deployment could either watch all services in all namespaces (when argument --namespace is blank) or only watch services in specific namespace  (when give argument --namespace a namespace value). 

is your concern about if service "nginx-deploy-svc" not exist in namespace "cka", the k8s-bigip-ctrl watching namespace "cka" could logs "Service 'nginx-deploy-svc' has not been found.", but not deleting the the POD ARP record on BIGIP deployed by k8s-bigip-ctrl watching namespace "k8s" ?

**Comment by vincentmli** [comment]
> Anothe test also show in vxlan mode, we can not deploy multi cc that connect to the same BIGIP
> Try set as below :
> -- | -- | -- | -- | -- | --
> Ns1 | Cc1 | Svc1 | cm1 | Partition 1 | Route domain1
> -- | -- | -- | -- | -- | --
> Ns2 | Cc2 | Svc2 | cm2 | Partition2 | Route domain 2
> 
> You will find cc1 will delete the static arp that created by cc2, cc2 will delete the static arp that created by cc1.
> 
> ```
> 2018/12/30 16:16:46 [INFO] [2018-12-30 16:16:46,277 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.68
> 2018/12/30 16:16:46 [INFO] [2018-12-30 16:16:46,305 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.18
> 2018/12/30 16:16:46 [INFO] [2018-12-30 16:16:46,333 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.30
> 2018/12/30 16:16:46 [INFO] [2018-12-30 16:16:46,372 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.74
> ```
> ```
> 2018/12/30 16:18:50 [INFO] [2018-12-30 16:18:50,686 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
> 2018/12/30 16:19:20 [INFO] [2018-12-30 16:19:20,602 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.1.30
> 2018/12/30 16:19:20 [INFO] [2018-12-30 16:19:20,635 f5_cccl.resource.resource INFO] Creating ApiArp: /Common/k8s-10.244.0.74
> 2018/12/30 16:19:20 [INFO] [2018-12-30 16:19:20,664 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.68
> 2018/12/30 16:19:20 [INFO] [2018-12-30 16:19:20,700 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.1.18
> ```

not sure if it helps, have you tried to create two different self ip and two fake BIGIP nodes  for each CC according to https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-bigip-k8s.html

**Comment by vincentmli** [comment]
here is my debug log:

nginxservice not existed in k8s namespace
<pre>
2018/12/31 20:35:34 [DEBUG] Process Service delete - name: nginxservice namespace: k8s
2018/12/31 20:35:34 [INFO] Port '80' for service 'nginxservice' was not found.
2018/12/31 20:35:34 [INFO] Service 'nginxservice' has not been found.
2018/12/31 20:35:34 [DEBUG] Updated 1 of 0 virtual server configs, deleted 0
</pre>

result in no virtual server created, no pod arp created, and only fdb entry created in /tmp/k8s-bigip-ctlr.config717653002/config.json
<pre>
2018/12/31 20:35:34 [DEBUG] AppManager wrote endpoints to VxlanMgr.
2018/12/31 20:35:34 [DEBUG] ConfigWriter (0xc0003878c0) writing section name resources
2018/12/31 20:35:34 [DEBUG] ConfigWriter (0xc0003878c0) successfully wrote section (resources)
2018/12/31 20:35:34 [INFO] Wrote 0 Virtual Server and 0 IApp configs
2018/12/31 20:35:34 [DEBUG] LTM Resources: {}
2018/12/31 20:35:34 [DEBUG] Finished syncing virtual servers {Namespace:k8s ServiceName:nginxservice} (2.755029ms)
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,796 __main__ DEBUG] config file /tmp/k8s-bigip-ctlr.config717653002/config.json changed - signalling bigip
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,796 __main__ DEBUG] config handler woken for reset
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,797 __main__ DEBUG] loaded configuration file successfully
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,797 __main__ DEBUG] NET Config: {"userFdbTunnels": [{"records": [{"endpoint": "10.169.72.93", "name": "ee:5c:1e:b4:5e:7d"}], "name": "flannel_vxlan"}]}

</pre>

https://github.com/f5devcentral/f5-ctlr-agent  invokes https://github.com/f5devcentral/f5-cccl to apply_ltm_config and apply_net_config to BIGIP

<pre>
018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,797 f5_cccl.service.manager DEBUG] apply_ltm_config start
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,797 f5_cccl.service.validation DEBUG] Validating desired config against CCCL API schema.
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,797 f5_cccl.service.validation DEBUG] validate start
2018/12/31 20:35:34 [DEBUG] [2018-12-31 20:35:34,797 f5_cccl.service.validation DEBUG] validate took 0.00026 seconds.

2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,511 f5_cccl.service.manager DEBUG] apply_net_config start
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,511 f5_cccl.service.validation DEBUG] Validating desired config against CCCL API schema.
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,511 f5_cccl.service.validation DEBUG] validate start
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,512 f5_cccl.service.validation DEBUG] validate took 0.00050 seconds.
</pre>

Notice the net config change to BIGIP Common partition
<pre>

2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,526 f5_cccl.bigip DEBUG] Refreshing the BIG-IP net cached state...

2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,597 f5_cccl.bigip DEBUG] Retrieving arps from BIG-IP /Common...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,597 root DEBUG] get WITH uri: https://10.169.72.34:443/mgmt/tm/net/arp/ AND suffix:  AND kwargs: {'params': '$filter=partition+eq+Common'}

2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,682 f5_cccl.service.manager DEBUG] Getting arp tasks...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Getting tunnel tasks...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Getting pre-existing tunnel update tasks...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Building task lists...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Service task queue length: 2
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Creating 0 resources...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Updating 0 resources...
2018/12/31 20:35:36 [DEBUG] [2018-12-31 20:35:36,683 f5_cccl.service.manager DEBUG] Deleting 2 resources...
2018/12/31 20:35:36 [INFO] [2018-12-31 20:35:36,683 f5_cccl.resource.resource INFO] Deleting IcrArp: /Common/k8s-10.244.0.45

</pre>

this means both CCs that manage same BIGIP would update the ARP record in BIGIP "Common" partition regardless what k8s namespace or BIGIP partition the CC manages. this is design issue, I am wondering if ARP can be created in the partition that CC manages instead of put ARP in "Common" partition.

 I noticed you attempted to use BIGIP route domain to separate the network namespace on BIGIP, I think there needs to be some kind of network separation the CC manages if running multiple CCs to one BIGIP, otherwise, this can be very problematic.

**Comment by myf5** [comment]
Hi Vincent, Happy new year.
"nginx-deploy-svc"  is in the default ns.  mapping to k8s partition.  
I  created 2 cc, one for  default ns (and mapping to k8s partition, route domain 0), one for cka ns(mapping to cka partition, route domain 10). 

Here I actually create a fake route-domain 10 (as I have not found how to create tunnels for separation containers, this should be restricted by flannel self, as flannel seem like actually can not do  containers isolation by vxlan).  

Just as your test, cc does not aware of route-domain when creating/updating fdb/arp . This is ok I think since most of network mode for K8S is not support this kind if isolation (Remember Cisco Contiv supports, but not sure). 

The problem is , we should avoid deleting other cc's "resource" when a cc can not find his "resource" .  resource here I mean fdb/arp.

**Comment by vincentmli** [comment]
I will try to create arp/fdb in non-Common partition and see if it resolves the issue, by the way, what is the business design logic to use multiple CC to same BIGIP?

**Comment by myf5** [comment]
most of China local PaaS vendors support NS isolation to support development/QA/pre-production, they design an upper system to manage these, so to customer the PaaS just like multi tenants. We also need support this.

**Comment by vincentmli** [comment]
manually using tmsh to create static pod ARP in the partition that CC manages works 

<pre>
 # tmsh create net arp /test/k8s-10.244.0.44 ip-address 10.244.0.45 mac-address ee:5c:1e:b4:5e:7d

# ping 10.244.0.45
PING 10.244.0.45 (10.244.0.45) 56(84) bytes of data.
64 bytes from 10.244.0.45: icmp_seq=1 ttl=63 time=1.01 ms
64 bytes from 10.244.0.45: icmp_seq=2 ttl=63 time=0.781 ms

</pre>

now it is matter of feeding the partition info from CC to f5-ctlr-agent/f5-cccl so when f5-cccl make REST call to BIGIP to create net arp, it should have the partition info, right now the CC code only feed f5-ctlr-agent/f5-cccl with no partition info so static pod net arp entry always created in default "Common" partition

<pre>
func (vxm *VxlanMgr) addArpForPods(pods interface{}, kubeClient kubernetes.Interface) {
	arps := arpSection{}

	for _, pod := range pods.([]appmanager.Member) {
		var mac string
		mac, err = getVtepMac(pod, kubePods, kubeNodes)
		if nil != err {
			log.Errorf("%v", err)
			return
		}
		entry := arpEntry{
			Name:    fmt.Sprintf("k8s-%v", pod.Address),
			IPAddr:  pod.Address,
			MACAddr: mac,
		}
		arps.Entries = append(arps.Entries, entry)
	}
</pre>


There is still a problem though, when two CC deploy different configmap with same k8s service, since the same k8s service map to same pod, there will still be conflicting error with creating  same pod arp on BIGIP   in different BIGIP partition,  different configmap using same k8s service can be problematic.  Maybe route domain is better isolation, I am not sure if VXLAN implementation in BIGIP support route domain, has to check, this can be complicate ;)

**Comment by vincentmli** [comment]
is it very common requirement that different configmap/ingress reference same k8s service in same CC or in different CC? I have to ask this because creating net arp in non-Common partition will not resolve the problem unless the k8s service is different

**Comment by mdditt2000** [comment]
Traditionally its an k8s service per CC per big-ip.

**Comment by vincentmli** [comment]
it turned out there is already code to deal with creating pod arp in CC BIGIP partition instead of default Common partition

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/cmd/k8s-bigip-ctlr/main.go#L617

<pre>
	// If running in VXLAN mode, extract the partition name from the tunnel
	// to be used in configuring a net instance of CCCL for that partition
	var vxlanPartition string
	if len(vxlanName) > 0 {
		cleanPath := strings.TrimLeft(vxlanName, "/")
		slashPos := strings.Index(cleanPath, "/")
		if slashPos == -1 {
			// No partition
			vxlanPartition = "Common"
		} else {
			// Partition and name
			vxlanPartition = cleanPath[:slashPos]
		}
	}
</pre>

so in your each CC deployment, give the   argument  --flannel-name the partition name the CC manages, then the pod arp will be created in the partition instead of "Common" partition

for example, in your case:

<pre>
            "--bigip-partition=k8s",
            "--namespace=default",
            "--pool-member-type=cluster",
            "--flannel-name=/k8s/flannel_vxlan",
</pre>

and

<pre>
            "--bigip-partition=cka",
            "--namespace=cka",
            "--pool-member-type=cluster",
            "--flannel-name=/cka/flannel_vxlan",
</pre>

this seems not documented anywhere and I have to read through the code to figure that out, I tested  and it seems working. Please test and see if you still have problem, probably there still is that I am missing ;)

**Comment by myf5** [comment]
> is it very common requirement that different configmap/ingress reference same k8s service in same CC or in different CC? I have to ask this because creating net arp in non-Common partition will not resolve the problem unless the k8s service is different
Not 100% sure it is common, but I can see many discussion about how to let Ingress(nginx) across NS.

**Comment by myf5** [comment]
> it turned out there is already code to deal with creating pod arp in CC BIGIP partition instead of default Common partition
> 
> https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/cmd/k8s-bigip-ctlr/main.go#L617
> 
> 	// If running in VXLAN mode, extract the partition name from the tunnel
> 	// to be used in configuring a net instance of CCCL for that partition
> 	var vxlanPartition string
> 	if len(vxlanName) > 0 {
> 		cleanPath := strings.TrimLeft(vxlanName, "/")
> 		slashPos := strings.Index(cleanPath, "/")
> 		if slashPos == -1 {
> 			// No partition
> 			vxlanPartition = "Common"
> 		} else {
> 			// Partition and name
> 			vxlanPartition = cleanPath[:slashPos]
> 		}
> 	}
> so in your each CC deployment, give the argument --flannel-name the partition name the CC manages, then the pod arp will be created in the partition instead of "Common" partition
> 
> for example, in your case:
> 
>             "--bigip-partition=k8s",
>             "--namespace=default",
>             "--pool-member-type=cluster",
>             "--flannel-name=/k8s/flannel_vxlan",
> and
> 
>             "--bigip-partition=cka",
>             "--namespace=cka",
>             "--pool-member-type=cluster",
>             "--flannel-name=/cka/flannel_vxlan",
> this seems not documented anywhere and I have to read through the code to figure that out, I tested and it seems working. Please test and see if you still have problem, probably there still is that I am missing ;)

Great finding.

**Comment by vincentmli** [comment]
for the complete info, here is the code that vlxan partition passed on to f5-ctrl-agent

https://github.com/f5devcentral/f5-ctlr-agent/blob/master/f5_ctlr_agent/bigipconfigdriver.py#L805
<pre>
        if vxlan_partition:
            # Management for net resources (VXLAN)
            manager = CloudServiceManager(
                bigip,
                vxlan_partition,
                user_agent=user_agent,
                prefix=args.ctlr_prefix,
                schema_path=_find_net_schema())
            managers.append(manager)
</pre>

**Comment by myf5** [comment]
Hi Vincent,
I think the partition name for vxlan here is still not for separating network traffic.   
If I set below 2 cc:
```
            "--bigip-partition=k8s",
            "--namespace=default",
            "--pool-member-type=cluster",
            "--flannel-name=/k8s/flannel_vxlan",
```
And
```
            "--bigip-partition=cka",
            "--namespace=cka",
            "--pool-member-type=cluster",
            "--flannel-name=/cka/flannel_vxlan",
```
The prerequisites is I need set 2 tunnels in different partitions. The problem here is, BIGIP disallow set 2 tunnel with same Key ID when using same vtep addr:
`010716ce:3: The tunnel /cka/test must have a unique VNI - the specified VNI(1) conflicts with VNI of tunnel /Common/flannel_vxlan.`

This is not F5 issue, flannel need support setting VNI for different NS.

And, if try to set different tunnel with different VLAN(vtep) in bigip. Tunnels will be created successfully(same Key id=1).  So to flannel, that just like 2 different nodes(but actually both on the same BIGIP). Then you need create self ip for each tunnel,  at this time, bigip will tell you the same net can not be on 2 different vlan:

`Self IP 10.244.246.2 / 255.255.0.0: This network is defined on two vlans (/cka/rd10_flannel_vxlan and /Common/flannel_vxlan)`

Summary:
CC does support partition, and also support RD when writing network into bigip. 
But for k8s network separation, the k8s network mode self should support separation first.

Pls correct me if my understanding is wrong.

**Comment by vincentmli** [comment]
BIGIP partition does not separate network, it is to separate configuration object for administration, route domain (same as Linux network namespace) is to separate the network, have you tried to put the route domain notation %10 for the rd10 tunnel self ip and the network ?

**Comment by myf5** [comment]
> BIGIP partition does not separate network, it is to separate configuration object for administration, route domain (same as Linux network namespace) is to separate the network, have you tried to put the route domain notation %10 for the rd10 tunnel self ip and the network ?

yeah, I did not refresh this page, and directly edit my post. ( I had noticed that wrong setting and correct that but get other issue then, pls check the revised post :)

**Comment by vincentmli** [comment]
in regard to flannel, flannel hard coded the VNI to be 1 and not configurable 
https://github.com/coreos/flannel/blob/master/backend/vxlan/vxlan.go#L74
<pre>
const (
	defaultVNI = 1
)

func (be *VXLANBackend) RegisterNetwork(ctx context.Context, wg sync.WaitGroup, config *subnet.Config) (backend.Network, error) {
	// Parse our configuration
	cfg := struct {
		VNI           int
		Port          int
		GBP           bool
		DirectRouting bool
	}{
		VNI: defaultVNI,
	}

	if len(config.Backend) > 0 {
		if err := json.Unmarshal(config.Backend, &cfg); err != nil {
			return nil, fmt.Errorf("error decoding VXLAN backend config: %v", err)
		}
	}
	log.Infof("VXLAN config: VNI=%d Port=%d GBP=%v DirectRouting=%v", cfg.VNI, cfg.Port, cfg.GBP, cfg.DirectRouting)

	devAttrs := vxlanDeviceAttrs{
		vni:       uint32(cfg.VNI),
		name:      fmt.Sprintf("flannel.%v", cfg.VNI), <===the tunnel name flannel.1
		vtepIndex: be.extIface.Iface.Index,
		vtepAddr:  be.extIface.IfaceAddr,
		vtepPort:  cfg.Port,
		gbp:       cfg.GBP,
	}

	dev, err := newVXLANDevice(&devAttrs)
	if err != nil {
		return nil, err
	}
</pre>

if creating two VXLAN tunnel on BIGIP, maybe the k8s cluster may also need two flannel  with different VNI
flannel code may need to be hacked to add custom VNI

**Comment by myf5** [comment]
Flannel does support VNI setting, but that still for global. 
Create 2 flannel is interesting, not sure this is ok. Maybe the content in etcd maybe overwrite.

**Comment by vincentmli** [comment]
let me see if you have misunderstood me, when I say do this:
<pre> 
           "--bigip-partition=k8s",
            "--namespace=default",
            "--pool-member-type=cluster",
            "--flannel-name=/k8s/flannel_vxlan",
And

            "--bigip-partition=cka",
            "--namespace=cka",
            "--pool-member-type=cluster",
            "--flannel-name=/cka/flannel_vxlan",
</pre>

I did not mean you need to create two flannel_vxlan tunnel on BIGIP, the only purpose of giving /<partition>/flannel_vxlan is to create pod arp in /<partition> so two CC does not mess with each others pod arp configuration objects in BIGIP. 

if you really need to have network separation for two CCs, that is complex topic and needs to be thought through ;)

**Comment by myf5** [comment]
suggest note this in the document when creating multi cc for multi ns.
            "--bigip-partition=k8s",
            "--namespace=default",
            "--pool-member-type=cluster",
            "--flannel-name=/k8s/flannel_vxlan",
and

            "--bigip-partition=cka",
            "--namespace=cka",
            "--pool-member-type=cluster",
            "--flannel-name=/cka/flannel_vxlan",
