### ISSUE TITLE
NodePort configuration exposes IPs of all nodes in cluster

### ISSUE THREAD

**Issue by codereflection** [F5Networks/k8s-bigip-ctlr#901]
#### Description
We're using NodePort configuration to expose services in a 3 node cluster (say they are named node1, node2, & node3).  The issue is that every node's IP address is exposed via the Big IP, instead of only the nodes where the pods are actually scheduled.  For example, if I scale down to 1 pod, the VIP on the BigIP still shows all 3 node's IP addresses, with the two nodes where the pods are _not_ scheduled showing failing health checks.   When I scale back up enough that the pods are on all three nodes, the health checks from the Big IP return to green.  It seems like the selectors are possibly grabbing every cluster node's IP instead of only the nodes where the pods are scheduled.

#### Kubernetes Version
v1.13.4

#### Controller Version
v1.8.1

#### BIG-IP Version
12.1.2

#### Diagnostic Information

k8s-bigip-ctlr-deployment.yml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:1.8.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=[REDACTED]",
            "--bigip-partition=k8s-kong-dev",
            "--namespace=default",
            "--pool-member-type=nodeport",
            "--node-poll-interval=35",
            "--verify-interval=120",
            "--log-level=INFO"
            ]
```

service-configmap.yml:
```
# proxy port 8000
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-proxy
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "k8s-kong-dev",
          "virtualAddress": {
            "bindAddr": "[REDACTED]",
            "port": 8000
          }
        },
        "backend": {
          "serviceName": "kong-proxy",
          "servicePort": 8000,
          "healthMonitors": [{
            "interval": 5,
            "protocol": "http",
            "send": "GET / HTTP/1.1\r\nHost: health-check\r\nConnection: keep-alive\r\nPragma: no-cache\r\nCache-Control: no-cache\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: f5-big-ip [kong-proxy]\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-US,en;q=0.9",
            "timeout": 16
          }]
        }
      }
    }
```

service.yml:
```
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: kong
```

Getting the nodes:
```
$ kubectl get nodes -o=wide
NAME            STATUS   ROLES                      AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready    controlplane,etcd,worker   20h   v1.13.4   [REDACTED-NODE1-IP]   <none>        Ubuntu 16.04.4 LTS   4.4.0-133-generic   docker://18.9.2
node2   Ready    controlplane,etcd,worker   20h   v1.13.4   [REDACTED-NODE2-IP]   <none>        Ubuntu 16.04.4 LTS   4.4.0-133-generic   docker://18.9.2
node3   Ready    controlplane,etcd,worker   20h   v1.13.4   [REDACTED-NODE3-IP]   <none>        Ubuntu 16.04.4 LTS   4.4.0-133-generic   docker://18.9.2
```

Getting the list of running pods:
```
$ kubectl get pods -o=wide -l app=kong
NAME                       READY   STATUS    RESTARTS   AGE   IP          NODE            NOMINATED NODE   READINESS GATES
kong-rc-696c8d799b-vl6ls   1/1     Running   0          18h   10.42.0.7   node2   <none>           <none>
```

Controller pod log after applying the `service-configmap.yml`:
```
2019/04/18 16:52:36 [INFO] Wrote 1 Virtual Server and 0 IApp configs
2019/04/18 16:52:37 [INFO] [2019-04-18 16:52:37,131 f5_cccl.resource.resource INFO] Creating ApiHTTPMonitor: /k8s-kong-dev/cfgmap_default_kong-proxy_kong-proxy_0_http
2019/04/18 16:52:37 [INFO] [2019-04-18 16:52:37,318 f5_cccl.resource.resource INFO] Creating ApiPool: /k8s-kong-dev/cfgmap_default_kong-proxy_kong-proxy
2019/04/18 16:52:37 [INFO] [2019-04-18 16:52:37,523 f5_cccl.resource.resource INFO] Creating ApiVirtualServer: /k8s-kong-dev/default_kong-proxy
```

Resulting Network Traffic Map:
```
- default_kong-proxy
 - cfgmap_default_kong-proxy_kong-proxy
   - [REDACTED-NODE1-IP]:30058
   - [REDACTED-NODE2-IP]:30058
   - [REDACTED-NODE3-IP]:30058
```

In that network map, NODE1 and NODE3 are failing health checks, because there are no pods scheduled for the app on those nodes, and NODE2 is green as expected.

**Comment by rsalsa** [comment]
Hi @codereflection - when a service is exposed using the NodePort type, K8S makes that service available on each node in the cluster, regardless if the pod is scheduled on that node or not. That is why you see the BIG-IP pool contain all the nodes in your cluster. If you use something like a VXLAN or BGP overlay that the BIG-IP can be a part of, then you'll see only the POD IPs in the BIG-IP pool. 

As for the failing pool members, I think this is something we can check. When you scale down to 1 single pod, can you confirm on the other cluster nodes that the ephemeral port is in a listening state with something like netstat?

**Comment by codereflection** [comment]
Thanks for the quick response @rsalsa.  I've looked at netstat on the other nodes, as well as the logs for kube-proxy, and the ports are definitely in a listening state on all of the nodes.  However, successful connections can only be established through the node hosting the pod.  

I've found a related issue here.  It's possible that this is a k8s v1.13 issue.  https://github.com/kubernetes/kubernetes/issues/72712

**Comment by codereflection** [comment]
Closing because this seems to be a routing issue with k8s configuration of iptables, and nothing to do with the f5 controller.

**Comment by mdditt2000** [comment]
@codereflection please give CIS 1.9 a spin using an AS3 declaration. Here are a few working examples. https://github.com/mdditt2000/kubernetes/blob/dev/cis-1-9/A3/f5-as3-configmap.yaml

**Comment by codereflection** [comment]
Thanks @mdditt2000, I will give 1.9 a go.

Also - the issue turned out to be having `externalTrafficPolicy` set to `Local`, which has the documented behavior of what I described. TIL.

**Comment by codereflection** [comment]
@rsalsa @mdditt2000 
Thinking more about this issue.  When `externalTrafficPolicy` is set to `local`, would it make sense for this controller to detect which nodes are running the pods and only use those IP addresses for the VIP configuration on the Big IP?  The documentation [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport) states that 

> Setting service.spec.externalTrafficPolicy to the value Local will only proxy requests to local endpoints, never forwarding traffic to other nodes and thereby preserving the original source IP address. If there are no local endpoints, packets sent to the node are dropped, so you can rely on the correct source-ip in any packet processing rules you might apply a packet that make it through to the endpoint.

**Comment by codereflection** [comment]
@rsalsa @mdditt2000 any thoughts on my last comment there?

**Comment by chen23** [comment]
@codereflection  Would a health monitor "solve" the issue?  On the nodes with Pods you would get a healthy response plus traffic and nodes w/out would not get traffic.

**Comment by codereflection** [comment]
@chen23 yeah, it would solve the issue, it seems to be taking it as a backwards approach though.  Why publish IP's of nodes where the controller can preemptively tell that specific nodes are not running a workload?

**Comment by chen23** [comment]
@codereflection good point.  I'd +1 that idea to only list nodes where a minimum of 1 Pod is running for the use case that you describe.

**Comment by sfudeus** [comment]
Some thought on our experiences with this issue: 
As described, in nodeport mode, always all nodes are submitted as pool member, regardless of if they carry an active/healthy endpoint and/or the externalTrafficPolicy of the service. The health check ensures that (with externalTrafficPolicy="local") only traffic is sent to pods carrying endpoints. Nonetheless, many health checks are done here superfluously, esp. on larger cluster with small deployments. 
Caveat: When a node join the pool, the health state is initially unknown until the health check has first established a state. During this time, traffic is sent even to those nodes not carrying a pod, leading to dropped traffic. We'll shortly open a specific issue here with a proposed fix for it. 

We, too, would prefer that even in nodeport mode only those nodes nodes are submitted as pool member which do carry a relevant pod (as for the vxlan mode endpoint lists are considered already).

**Comment by rsalsa** [comment]
@sfudeus & @codereflection - is using NodePort a requirement in your environments? Running with externalTrafficPolicy="local" in a K8S environment isn't ideal as traffic from within the cluster could potentially end up at a node that does not run the pod, thereby having the traffic dropped. 

Having the BIG-IP as a part of the cluster network (if possible) leads to a more accurate pool as only active endpoints are included in the pool.

**Comment by codereflection** [comment]
@rsalsa it is only from the perspective that I need the source IP addresses of the device access the service that k8s is managing. 

We're using k8s to manage our Kong environment.  So tracking calls made to API's behind Kong requires that we log out the calling IP address to those clients.  The only want to maintain the calling IP address is through externalTrafficPolicy="local".  If the big ip could inject the actual calling IP address into a different header, I could configure Kong to pull the calling IP address out of a different header, but I'm not sure that we can do that with the big ip...

**Comment by rsalsa** [comment]
@codereflection - Thank you. You'll want to subscribe to #693 for updates on this enhancement. 

In the meantime, this should be possible if you use the [F5 AS3 integration](https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html) with the Controller. You'd accomplish this by adding an [HTTP Profile to insert the headers](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#http-profile-insertheader).

**Comment by sfudeus** [comment]
@codereflection Shouldn't it be an easy thing for http traffic to have F5 inject an X-Forwarded-For header e.g. via iRule? 

@rsalsa Yes, NodePort is currently a requirement for us, since vxlan integration currently requires to disable automatic sync between the F5-HA-pair, since the vxlan connection may not be synced (see e.g. https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-tmos-tunnels-ipsec-13-1-0/2.html). 
Traffic policy cluster in comparison to local leads to 
a) unnecessary east-west traffic within the cluster sind an additional load balancing occurs (after having passed a dedicated load balancer). 
b) session persistence is not possible (it is not guaranteed with "local" either, given that multiple pods exist on the same host, granted)

Generally, a pool member monitor would prevent traffic being sent to nodes not carrying a workload pod, if traffic in unknown state would not be sent there. As said, we'll open a dedicated issue with a proposal soon. 


Additional note: 
The option to only report nodes with active endpoints should of course be only added as an additional mode between nodeport and vxlan, since it depends on how many nodes of your cluster are really used as an ingress node. Selecting only those with active endpoints should only be done if in general all worker nodes are eligible ingress nodes. If only a subset of the workers is designated as ingress node from f5 via label selection, then one couldn't expect that all workload is directly reachable on an ingress node (at least with externalTrafficPolicy "local").

**Comment by rsalsa** [comment]
Thanks for the additional info, @sfudeus. 

> @rsalsa Yes, NodePort is currently a requirement for us, since vxlan integration currently requires to disable automatic sync between the F5-HA-pair, since the vxlan connection may not be synced.

While this piece of documentation references deploying a BIG-IP HA configuration in an [OpenShift deployment](https://clouddocs.f5.com/containers/v2/openshift/kctlr-openshift-bigip-ha.html), you can accomplish the same thing with K8S. The HA pair would be seen as individual nodes with their own subnet in the overlay network. 

Our current recommendation is to deploy one `k8s-bigip-ctlr` per BIG-IP device rather than use config sync between the HA pair. Each individual `k8s-bigip-ctlr` would keep its BIG-IP up to date with the K8S environment. 

Would this help in your environment?

**Comment by dgarrisonf5** [comment]
For customers wanting to use F5 Container Ingress Services with a BIG-IP HA pair and config auto-sync, I would recommend deploying Calico BGP as the K8S or OCP CNI and configure BGP on the BIG-IP.

There are several advantages to using Calico BGP:

- K8S and OCP cluster mode services supported which means only one layer of load balancing (no iptables).
-  BIG-IP health monitors accurately reflect the health of the application instances
- Pure layer 3 which mean no overlay network which also simplifies troubleshooting
- No need to allocate subnets in K8S or OCP for the BIG-IP instances
- Can use BIG-IP HA with config auto-sync because each BIG-IP forms BGP neighbor relationships

**Comment by sfudeus** [comment]
@rsalsa 
I am aware of the recommendation, though it means that we need dedicated BIGIP devices for the kubernetes clusters and we cannot share the setup with traditional host-based and statically configured instances. 

@dgarrisonf5 
We already use calico with BGP, but our PodCidr ranges are not routable from F5 (or even from outside of k8s), which is why a tunneling mechanism would be required. Or would it be possible to let the BIG-IP instance know via BGP the host-ip as next-hop for the respective pod subnets? Ist there some documentation for this?

**Comment by dgarrisonf5** [comment]
hi @sfudeus.  not knowing your architecture, but would multi-hop ebgp work for you?  it allow for bgp neighbor relationships to be formed when there are one or more routers between the bgp peers.

You can find info on how to do it on the BIG-IP here:

https://support.f5.com/csp/article/K54334475#2

Not knowing who your router vendor is, but it's very likely that ebgp multi-hop is supported.

**Comment by rsalsa** [comment]
@sfudeus - Yes, you can use Calico with the BIG-IP where BGP is set up between your K8S nodes and the BIG-IP so that we can see the next-hop information:

`
B       192.168.0.0/24 [200/0] via 172.24.171.55, wan, 22:25:00
`

Details on the configuration can be referenced in our [K14436300: Connecting the BIG-IP system to a Calico BGP Kubernetes cluster](https://support.f5.com/csp/article/K14436300) support article.

**Comment by sfudeus** [comment]
Thx, will verify this with our network team. Given this makes the podCIDR routable, will this work then with the vxlan mode of the bigip-ctrl, not establishing tunnels, but only use podIPs from the endpoint lists as pool members?

**Comment by dgarrisonf5** [comment]
Hi @sfudeus.  Not sure if your comment is in response to what I said or what @rsalsa said but, if it's in response to what I said, you would not use VxLAN on the BIG-IP but rather BGP.

**Comment by sfudeus** [comment]
Hi @dgarrisonf5, it was in reply to you, but I was referring to the mode the  F5-bigip-ctrl would operate in. IIRC there only are the nodeport mode, using all label selected k8s nodes on the services' node ports, or the vxlan mode, using the pods' addresses from the services' endpoints list. I was curious if the latter mode would implicitly require a tunnel being set up, even when routing is already possible via bgp.

**Comment by rsalsa** [comment]
@sfudeus, you will run your `k8s-bigip-ctlr` in `cluster` mode (pool-member-type), so the controller will read the Endpoints for the Services to be able to route to exposed pods directly.

**Comment by dgarrisonf5** [comment]
Hi @sfudeus.  Actually, the two different modes of operation are "nodeport" and "cluster" where cluster mode is when the BIG-IP can be part of the cluster network - whether that is using VxLAN or BGP on the BIG-IP.

BGP is a layer 3 protocol and does NOT require a tunneling mechanism to work.

**Comment by kunalpuriii** [comment]
Hello All
I am trying to get the nodeport integration working with f5, it worked once after that nodes disappeared and did not work

Here is the config:
CIS controller:
   - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=https://192.168.5.210
        - --bigip-partition=k8s-AS3
        - --pool-member-type=nodeport
        - --agent=as3
        - --manage-ingress=false
        - --insecure=true
        - --as3-validation=true
        - --node-poll-interval=30
        - --verify-interval=30
        - --log-level=INFO

AS3 configmap
root@master-1:~# kubectl describe configmap f5-as3-declaration -n kube-system
Name:         f5-as3-declaration
Namespace:    kube-system
Labels:       as3=true
              f5type=virtual-server
Annotations:  <none>

Data
====
template:
----
{
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "http",
        "remark": "A1 example",
        "AS3": {
            "class": "Tenant",
            "A1": {
                "class": "Application",
                "template": "http",
                "serviceMain": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                        "10.1.1.4"
                    ],
                    "pool": "web_pool",
                    "virtualPort": 80
                },
                "web_pool": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [
                        {
                            "servicePort": 8080,
                            "serverAddresses": []
                        }
                    ]
                }
            }
        }
    }
}

Events:  <none>

Service associated with Ingress controller(NGINX)
root@master-1:~# kubectl describe svc f5-hello-world-web  -n nginx-ingress
Name:                     f5-hello-world-web
Namespace:                nginx-ingress
Labels:                   app=f5-hello-world-web
                          cis.f5.com/as3-app=A1
                          cis.f5.com/as3-pool=web_pool
                          cis.f5.com/as3-tenant=AS3
Annotations:              <none>
Selector:                 app=nginx-ingress
Type:                     NodePort
IP:                       10.103.216.254
Port:                     f5-hello-world-web  8080/TCP
TargetPort:               8080/TCP
NodePort:                 f5-hello-world-web  32201/TCP
Endpoints:                10.1.1.16:8080,10.1.1.21:8080,10.1.2.34:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

Looking forward to a response

**Comment by kunalpuriii** [comment]
@codereflection @sfudeus 
Hello Guys
have we reached to any conclusion? will there by enhancement to include only the nodes with ingress controller running ?

We are using kube-router but only limited to K8's setup, we are not using dynamic protocol its all static routing in place. so advertising POD network is not an option.

Looking forward to your response.

Thanks
Kunal

**Comment by codereflection** [comment]
@kunalpuriii I'm not sure if they'll make the requested change at all.  For our purposes we're either making sure that all of the cluster nodes are running the pods, or just rely on the health checks from the Big IP to the nodes to know whether or not it's going to route traffic to any given pod.  Neither is idea, but we're not experiencing any traffic loss so it's good enough for now.

**Comment by kunalpuriii** [comment]
thanks @codereflection for your response, I guess we need to live with it for now or other thing is to move to cluster mode rather than node port. Did you consider moving to cluster mode?

**Comment by codereflection** [comment]
@kunalpuriii cluster mode isn't an option for us.  I can't remember the details of why at the moment, but we thoroughly investigated it and had to go with node port.

**Comment by chen23** [comment]
Depending on whether you are using iptables or ipvs for kube-proxy a health monitor could help isolate to nodes where the services are running. 

‘’’
externalTrafficPolicy=local
‘’’
I have not tried this myself. Not sure it would work. Another related issue #815

**Comment by kunalpuriii** [comment]
@mdditt2000 Thanks for your help sofar, Do you have any update on this case?
@codereflection have you faced issue during downscale or upscale? I understand in your case all cluster nodes are running the pods, so it may not be the issue.

We have faced issues when downscale the Ingress controllers as health monitor takes 16 seconds to timeout a worker node and for those seconds traffic is dropped. It also happens When a node join the pool, the health state is initially unknown until the health check has first established a state. During this time, traffic is sent even to those nodes not carrying a pod, leading to dropped traffic.

If we move to cluster mode, we need to setup routing from F5 and Fabric(l3) to internal POD network, which means we need to ensure no IP conflict. Also we are using kube-router as CNI which does not establish BGP or routing North bound to F5 or Fabric.
So it is not an ideal option for us.

Can we optimize the code to only have worker nodes as pool member where Ingress controller is running  (https://github.com/F5Networks/k8s-bigip-ctlr/blob/6f4a2681b93324b9624cd736650148edd6f21e3f/pkg/appmanager/appManager.go#L2276)
func (appMgr *Manager) getEndpointsForNodePort(
	nodePort int32,
) []Member {
	nodes := appMgr.getNodesFromCache()
	var members []Member
	for _, v := range nodes {
		member := Member{
			Address: v.Addr,
			Port:    nodePort,
			Session: "user-enabled",
		}
		members = append(members, member)
	}

	return members
}

**Comment by mdditt2000** [comment]
Good morning @kunalpuriii - the best option is to create node label for the worker nodes as defined in this document https://github.com/mdditt2000/kubernetes-1-18/blob/master/kubernetes-faq.md#manage-node-labels

Using f5role=worker on worker nodes will show up as pool members. 
```
kubectl get nodes
NAME                         STATUS   ROLES    AGE     VERSION
k8s-1-18-master.example.com   Ready    master   7d19h   v1.18.0
k8s-1-18-node1.example.com    Ready    f5role   7d19h   v1.18.0
k8s-1-18-node2.example.com    Ready    f5role   7d19h   v1.18.0
```

**Comment by kunalpuriii** [comment]
@mdditt2000 thanks for you response, Will this allow only the worker nodes where ingress controller is running will be added in the POOL and not all the nodes?

**Comment by sfudeus** [comment]
@kunalpuriii that will add all nodes with that label, regardless of which pods are on them, and will rely on health checks. You might be interested in our talk at KubeCon tomorrow if you attend (https://sched.co/Zemo). We established a workaround for that issue. Ultimately, integrating F5 into the cluster via vxlan will be the proper solution.

**Comment by mdditt2000** [comment]
@kunalpuriii yes. When using nodeport, please use node label of say "worker" so only worker nodes get added to the load balancing pool. @sfudeus great presentation. Thank you for sharing

**Comment by kunalpuriii** [comment]
@sfudeus sorry could not join the session, Do we have recording of the session to know about workaround.

**Comment by sfudeus** [comment]
@kunalpuriii If you are on the conference, it will be available on demand rather fast. I can post the link here once it is available on YouTube.

**Comment by kunalpuriii** [comment]
> @kunalpuriii If you are on the conference, it will be available on demand rather fast. I can post the link here once it is available on YouTube.
Hello @sfudeus do we have this on youtube yet?

**Comment by sfudeus** [comment]
Yes, was just uploaded a few days ago: https://youtu.be/pmuzOWB64Sg

**Comment by MnrGreg** [comment]
@sfudeus with regards to your comment below:

_Caveat: When a node join the pool, the health state is initially unknown until the health check has first established a state. During this time, traffic is sent even to those nodes not carrying a pod, leading to dropped traffic. We'll shortly open a specific issue here with a proposed fix for it._

Do you know if is it still the case that new members are sent traffic before they are health checked? Was an issue opened for this?

Sounds like this is standard LTM behavior which will need to be addressed. Ideally a pool member should be added in offline mode until the health checks succeed.

**Comment by sfudeus** [comment]
@MnrGreg 
Yes, this is standard LTM behavior and a feature request was opened but might only be addressed in an upcoming major release, so not to be expected soonish. Most likely we will have switched to integrating the balancer into our pod overlay network by then, which makes that superfluous for us.

**Comment by mdditt2000** [comment]
This is standard LTM behavior. 

Ideally a pool member should be added in offline mode until the health checks succeed. This issue was originally opened for  NodePort configuration exposes IPs of all nodes in cluster. Using CIS 2.2 with node labels defined in the virtualservice solves this issue. Testing 

`
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-demo
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.108"
  host: mysite.f5demo.com
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: f5-demo
    servicePort: 80
    nodeMemberLabel: f5role=worker
`
https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.2/github/1531/virtual-server-80.yaml

Closing this issue out. Please open a new issue if you want to add Nodes offline, allowing health monitors to work before sending traffic
